global_seed: 777
seed: ${global_seed}
device_train_batch_size: 300 # will be recalculated - doesn't matter
global_train_batch_size: 1600
device_eval_batch_size: 300
device_train_microbatch_size: "auto"
vocabulary:
  remote: "s3://vevo-ml-datasets/vevo-scgpt/datasets/cellxgene_primary_2024-04-29_MDS/cellxgene_primary_2024-04-29_vocab.json"
  local: "vocab/vocab_2024-04-29.json"
model:
  name: vevo_scgpt
  d_model: 256 #512
  n_layers: 12 #12
  init_device: cpu
  expansion_ratio: 4.0
  transformer_activation: relu
  n_heads: 4
  norm_scheme: "pre"
  use_generative_training: True
  use_cell_conditioned_generation: False
  use_glu: False
  cell_emb_style: cls
  attn_config:
    attn_impl: triton
    attn_type: "grouped_query_attention"
    kv_nheads: 4
    attn_pdrop: 0.0
  norm_config:
    norm_type: "layernorm"
    eps: 1.0e-5
  expression_encoder:
    input_emb_style: "continuous"
    dropout: 0.1
    max_value: 512
    activation: relu
    use_norm: True
  gene_encoder:
    use_norm: True
  mvc:
    arch_style: "inner product"
    query_activation: "sigmoid"
  expression_decoder:
    n_outputs: 1
    n_layers: 1
    activation: "leaky_relu"
collator:
  do_padding: True
  pad_value: -2
  do_mlm: True
  do_binning: True
  mlm_probability: 0.5
  mask_value: -1
  max_length: 1024 #2048
  sampling: True
  data_style: "both"
  num_bins: 51
  right_binning: False
  use_junk_tokens: True
train_loader:
  dataset:
    remote: "s3://vevo-ml-datasets/vevo-scgpt/datasets/biased_ds_cellxgene_primary_2024-07-01_MDS/train/"
    local: "/vevo/datasets/biased_ds_cellxgene_primary_2024-07-01_MDS/train" #"/vevo/datasets/cellxgene-2024-04-29/train"
    download_timeout: 300
    allow_unsafe_types: True
    shuffle: True
    shuffle_seed: ${global_seed}
    num_canonical_nodes: 2
  drop_last: False
  num_workers: 8
  pin_memory: True
  prefetch_factor: 48
  persistent_workers: True
valid_loader:
  dataset:
    remote: "s3://vevo-ml-datasets/vevo-scgpt/datasets/cellxgene_primary_2024-04-29_MDS/val/"
    local: "/vevo/datasets/cellxgene-2024-04-29/val"
    download_timeout: 300
    allow_unsafe_types: True
    shuffle: False
    shuffle_seed: ${global_seed}
    num_canonical_nodes: 2
  drop_last: False
  num_workers: 8
  pin_memory: True
  prefetch_factor: 48
  persistent_workers: True
optimizer:
  name: decoupled_adamw
  lr: 3.0e-4
  betas:
    - 0.9
    - 0.95
  eps: 1.0e-08
  weight_decay: 1.0e-05
scheduler:
  name: cosine_with_warmup
  t_warmup: "0.05dur"
  t_max: "1dur"
  alpha_f: 0.1
algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0
  low_precision_layernorm: {}
precision: amp_bf16
eval_interval: "10000ba"
max_duration: "6ep"
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: DEFAULT
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
  verbose: true
callbacks:
  speed_monitor:
    window_size: 20
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}
loggers:
  wandb:
    project: vevo-scgpt
    log_artifacts: False
save_folder: "s3://vevo-ml-datasets/vevo-scgpt/models/{run_name}"
save_interval: "5000ba"
save_num_checkpoints_to_keep: 0 # Delete local copies of checkpoints
run_name: scgpt-25m-1024-fix-norm-apr24-data
save_overwrite: True
