model_dir: "/tahoe/mosaicfm/checkpoints/release/mosaicfm-3b"
ensembl_to_gene_symbol: "/tahoe/mosaicfm/datasets/vevo_merged_jan_2025/vevo_v2_ensembl_to_gene_name.json"
model_name: "mosaicfm-v2-3b"
input_path: "/tahoe/mosaicfm/datasets/msigdb/rep_1.h5ad.gz"
output_path: "/tahoe/mosaicfm/datasets/msigdb/gene_embeddings"
# Column in adata.var that contains gene names
gene_col: "feature_id"
# Inference parameters
batch_size: 32
max_length: 8192
# Whether to save the adata with cell embeddings
save_cell_embeddings: False
