paths:
  vocab_file: "/tahoe/mosaicfm/checkpoints/release/mosaicfm-3b/vocab.json"
  model_config_path: "/tahoe/mosaicfm/checkpoints/release/mosaicfm-3b/model_config.yml"
  collator_config_path: "/tahoe/mosaicfm/checkpoints/release/mosaicfm-3b/collator_config.yml"
  model_file: "/tahoe/mosaicfm/checkpoints/release/mosaicfm-3b/best-model.pt"
  output_dir: "/tahoe/mosaicfm/datasets/barotaxis/embeddings_tahoe_100m_mosaicfm_3B"

dataset:
  name: "tahoebio/Tahoe-100M"
  split: "train"
  streaming: False

data:
  batch_size: 128
  max_length: 2048
  num_workers: 8
  prefetch_factor: 8
  reserve_keys:
    - "BARCODE_SUB_LIB_ID"
    - "sample"
    - "cell_line_id"
    - "plate"
    - "drug"

model:
  attn_impl: "flash"
  use_attn_mask: false

parquet:
  chunk_size: 100000

output:
  prefix: "mosaicfm-3B"
