model_name: "mosaicfm-3b-prod-cont-MFMv2"

paths:
  model_path_root: "/tahoe/mosaicfm/checkpoints/release/${model_name}"
  vocab_file: "${paths.model_path_root}/vocab.json"
  model_config_path: "${paths.model_path_root}/model_config.yml"
  collator_config_path: "${paths.model_path_root}/collator_config.yml"
  model_file: "${paths.model_path_root}/best-model.pt"
  output_dir: "s3://vevo-ml-datasets/mosaicfm_v2/inference/${model_name}_tahoe_100m_embeddings"

dataset:
  name: "/tahoe/mosaicfm/datasets/Tahoe-100M-HF"
  split: "train"
  streaming: False
  cache_dir: "/tahoe/mosaicfm/datasets/HF_cache"

data:
  batch_size: 128
  max_length: 2048
  num_workers: 8
  prefetch_factor: 8
  reserve_keys:
    - "BARCODE_SUB_LIB_ID"
    - "sample"
    - "cell_line_id"
    - "plate"
    - "drug"

model:
  attn_impl: "flash"
  use_attn_mask: false

parquet:
  chunk_size: 100000

output:
  prefix: ${model_name}
